#!/bin/bash
docstr=$(cat <<EOS
/**
 * @brief {brief}
 * @docs docs/{dir}/{filename}.md
 */
EOS
)
echo "$docstr"

for dir in ./competitive/*; do
    dirb=$(basename "$dir")
    echo $dirb
    for fn in $dir/*.hpp; do
        fbn=$(basename "$fn")
        fbn_without_extension=$(basename -s ".hpp" "$fn")
    done
done