# Reference: https://github.com/NyaanNyaan/library
name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Rename g++
      run: sudo ln -s /usr/bin/g++ /usr/bin/g++-12

    - name: Run online tests
      env:
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
      run: oj-verify run -j 4 --tle --timeout 10
      working-directory: ./onlie_test
