#!/bin/bash
for d_par in */; do
    cd $d_par
    for d in */; do
        cd $d
        if [[ -f "make_cases.py" ]]; then
            echo "make cases from script."
            python make_cases.py
        fi
        g++-12 --std=c++17 -I ../../../ answer.cpp
        oj t -c "./a.out" --tle 20 -e 1e-6 -j 4
        cd ..
    done
    cd ..
done